FROM alpine:edge

# TODO: change to container registry
COPY --from=clangbuiltlinux/containers:llvm-project llvm-project/llvm/build/bin /usr/local/bin
COPY --from=clangbuiltlinux/containers:llvm-project /usr/local/lib /usr/local/lib
COPY --from=clangbuiltlinux/containers:llvm-project /usr/local/include /usr/local/include
RUN ln -s /usr/local/lib/x86_64-alpine-linux-musl/libc++abi.so.1 /usr/lib/. && \
  ln -s /usr/local/lib/x86_64-alpine-linux-musl/libc++.a /usr/lib/. && \
  ln -s /usr/local/lib/x86_64-alpine-linux-musl/libc++abi.a /usr/lib/. && \
  ln -s /usr/local/lib/x86_64-alpine-linux-musl/libc++.so.1 /usr/lib/. && \
  ln -s /usr/local/lib/x86_64-alpine-linux-musl/libunwind.so.1 /usr/lib/. && \
  ln -s /usr/local/lib/x86_64-alpine-linux-musl/libunwind.a /usr/lib/.

RUN apk add wget

RUN wget --no-clobber --no-verbose https://musl.libc.org/releases/musl-1.2.3.tar.gz && \
  tar xvf musl-1.2.3.tar.gz

# TODO: doesn't musl need the kernel headers?
#COPY --from=clangbuiltlinux/containers:linux /sysroot /sysroot

RUN mkdir musl-1.2.3/build
RUN cd musl-1.2.3/build && \
  CC=clang ../configure --prefix=/usr --syslibdir=/usr/lib

# TODO: build llvm-ar
RUN apk add make llvm13
RUN cd musl-1.2.3/build && \
  make -j$(nproc) AR=llvm-ar RANLIB=llvm-ranlib

RUN cd musl-1.2.3/build && \
  make -j$(nproc) DESTDIR=/sysroot install-headers

RUN cd musl-1.2.3/build && \
  make -j$(nproc) DESTDIR=/sysroot install-libs

COPY hello.c .
RUN clang --sysroot=/sysroot hello.c && ./a.out
