name: Push Container
description: Push a Container

inputs:
  registry:
    description: Server address of Docker registry.
    required: true
  username:
    description: Username used to login.
    required: true
  password:
    description: Password or PAT used to login.
    required: true

  image:
    description: The name of the image to push.
    required: true
  tag:
    description: The tag of the image to push.
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - shell: bash
      run: |
        docker push ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
