name: Build container images

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - '*/Containerfile'
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - '*/Containerfile'
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: null

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [qemu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: variables
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}
          file: ./${{ matrix.image }}/Containerfile
          platforms: linux/amd64
          push: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
          tags: |
            ghcr.io/clangbuiltlinux/${{ matrix.image }}:${{ steps.variables.outputs.date }}
            ghcr.io/clangbuiltlinux/${{ matrix.image }}:latest
