name: llvm-project (epoch 2)

on: workflow_dispatch
jobs:
  epoch2:
    name: stage 2
    runs-on: [self-hosted, x64]
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and test llvm-project
        uses: ./.github/actions/build-test-llvm-project
        with:
          file: Dockerfile.epoch2
          platforms: linux/amd64
          tags: ghcr.io/clangbuiltlinux/llvm-project:stage2

      - name: Login to ghcr.io
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr.io
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        run: |
          docker push ghcr.io/clangbuiltlinux/llvm-project:stage2
