name: stage 3 (epoch 3)

on: workflow_dispatch
jobs:
  epoch3:
    name: stage 3 (epoch 3)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./llvm-project
          file: ./llvm-project/Dockerfile.epoch3
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/clangbuiltlinux/llvm-project:stage3
      - name: Test statically linked clang
        run: bash ci/test-clang.sh
      - name: Push image to ghcr.io
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        run: |
          docker push ghcr.io/clangbuiltlinux/llvm-project:stage3
