name: stage 2 (epoch 2)

on: workflow_dispatch
jobs:
  epoch2:
    name: stage 2 (epoch 2)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./llvm-project
          file: ./llvm-project/Dockerfile.epoch2
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/clangbuiltlinux/llvm-project:stage2

      - name: Test statically linked clang
        run: bash ci/test-clang.sh

      - name: Login to GitHub Container Registry
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr.io
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        run: |
          docker push ghcr.io/clangbuiltlinux/llvm-project:stage2
