name: llvm-project (epoch 3)

on: workflow_dispatch
jobs:
  epoch3:
    name: stage 3
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            os: [self-hosted, arm64]
            platforms: linux/arm64
          - arch: x86_64
            os: [self-hosted, x64]
            platforms: linux/amd64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and test llvm-project
        uses: ./.github/actions/build-test-llvm-project
        with:
          file: Dockerfile.epoch3
          platforms: linux/amd64
          tags: ghcr.io/clangbuiltlinux/llvm-project:stage3

      - name: Login to ghcr.io
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr.io
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        run: |
          docker push ghcr.io/clangbuiltlinux/llvm-project:stage3
