name: stage 1 and 2 (epoch 1)

on: workflow_dispatch
jobs:
  epoch1:
    name: stage 1 and 2 (epoch 1)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./llvm-project
          file: ./llvm-project/Dockerfile.epoch1
          platforms: linux/amd64
          push: ${{ github.repository_owner == 'ClangBuiltLinux' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
          tags: |
            ghcr.io/clangbuiltlinux/llvm-project:stage2
